#!/usr/bin/env python
# coding: utf-8

# In[3]:


import pandas as pd
import numpy as np


# In[4]:


df=pd.read_csv("C:\\Users\\PARUL\\Downloads\\supply_chain - supply_chain.csv")


# In[5]:


df.head()


# In[8]:


import plotly.express as px
import plotly.io as pio
import plotly. graph_objects as go
pio.templates.default = "plotly_white"


# In[9]:


df.describe()


# # now lets get started with analyzing the supply chain by looking at the relationship between the price of product and the revenue genrated by them

# In[11]:


fig=px.scatter(df,x='Price',
              y='Revenue generated',
              color='Product type',
              hover_data=['Number of products sold'],
              trendline ="ols")
fig.show()


# # thus, the company derives more revenue from skincare produvt and the higher the price of skincare product the more revenue they generate . now lets have a  look at the sales by product type:

# In[23]:


sales_data=df.groupby('Product type')['Number of products sold'].sum().reset_index()
#sales_data
pie_chart=px.pie(sales_data ,
                 values='Number of products sold',
                 names='Product type',
                 hover_data=['Number of products sold'],
                 hole=0.5,
                 color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside',textinfo='percent+label')
pie_chart.show()


# # So 45% of the business comes from skincare products, 29.5% from haircare, and 25.5% from cosmetics. NOw lets have a look at the total revenue generated from shipping carriers:

# In[24]:


total_revenue=df.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig=go.Figure()
fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'],
                    y=total_revenue['Revenue generated']))
fig.update_layout(title='Totsl Revenue by Shipping Carrier',
                 xaxis_title='shipping carriers',
                 yaxis_title='revenue generated')
fig.show()


# # So the company is using three carriers for transportation, and Carrier B helps the company in generating more revenue. Now let's have a look at the Average lead time and Average Manufacturing Costs for all products of the company:

# In[28]:


avg_lead_time=df.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_cost=df.groupby('Product type')['Manufacturing costs'].mean().reset_index()
result=pd.merge(avg_lead_time,avg_manufacturing_cost,on='Product type')
result.rename(columns={'Lead time':'Average lead time','Manufacturing costs':'Average manufacturing costs'},inplace=True)
print(result)


# # Analyzing SKUs
# There's a column in the dataset as SKUs. You must have heard it for the very first time. So, SKU stands for Stock Keeping Units. They're like special codes that help companies keep track of all the different things they have for sale. Imagine you have a large toy store with lots of toys. Each toy is different and has its name and price, but when you want to know how many you have left, you need a way to identify them. So you give each toy a unique code, like a secret number only the store knows. This secret number is called SKU.

# In[30]:


revenue_chart=px.line(df, x='SKU',
                     y='Revenue generated',
                     title='Revenue Generated by SKU')
revenue_chart.show()


# # There's another column in the dataset as Stock levels. Stock levels refer to the number of products a store or business has in its inventory. Now let's have a look at the stock levels of each SKU:

# In[31]:


stock_chart=px.line(df, x='SKU',
                     y='Stock levels',
                     title='Stock levels by SKU')
stock_chart.show()


# # now lets have a look at the order quantity of each sku;

# In[33]:


order_quantity_chart=px.bar(df, x='SKU',
                     y='Order quantities',
                     title='Order quantities by SKU')
order_quantity_chart.show()


# # Cost analysis 
# now lets analyze the shipping cost of carriers

# In[34]:


shipping_cost_chart=px.bar(df, x='Shipping carriers',
                     y='Shipping costs',
                     title='Shipping costs by Carriers')
shipping_cost_chart.show()


# # In one of the above visualizations, we discovered that Carrier B helps the company in more revenue. It is also the most costly Carrier among the three. Now let's have a look at the cost distribution by transportation mode:

# In[35]:


transportation_chart=px.pie(df,
                           values='Costs',
                           names='Transportation modes',
                           title='cost distribution by transportation mode',
                           hole=0.5,
                           color_discrete_sequence=px.colors.qualitative.Pastel)
transportation_chart.show()
                            


# # So the company spends more on road and rail modes for transportation goods

# # analysie defect rate
# the defect rate in the supply chain refers to the percentage of products that have something wrong or are found broken after shipping. Let's have a look at the average defect rate of all product types:

# In[36]:


defect_rates_by_product=df.groupby('Product type')['Defect rates'].mean().reset_index()

fig=px.bar(defect_rates_by_product,x='Product type',y='Defect rates',
          title='Avg defect rates by product type')
fig.show()


# In[ ]:




